### ISSUE TITLE
How do I retrieve a check's account number?

### ISSUE THREAD

**Issue by smithbk** [moov-io/imagecashletter#240]
This is not a bug, but just a question.

Can you tell me how to use your APIs to retrieve the check account number?

On page 26 of the [X9.37 spec](https://www.frbservices.org/binaries/content/assets/crsocms/financial-services/check/setup/frb-x937-standards-reference.pdf), it says the following:

```
The On-Us Field of the MICR document is located between positions 14 and 31 of the MICR Line
of the item. It is also known as Fields 2, 3, & 4 of the MICR line, usually including the Process Control or
Transaction Code, Account Number and Field 4.
```

This seems to indicate that the account number is in the check's OnUs field, but the type of that field in your APIs is a string.  How do we extract the check's account number from this string?  Or does it come from some other API call?

Thanks,
Keith

**Comment by atonks2** [comment]
Hey @smithbk, our library doesn't currently have a method for extracting an account number from the OnUs field. According to ANSI x9.100-187 (2016), the field is not consistent between financial institutions, so we can't reliably extract the value:
> Because ANSI X9.100-160–1 allows paying banks flexibility in the design of the On-Us Field on their physical
checks, its structure can vary from bank to bank. Without knowing each paying bank’s On-Us Field structure, the
truncating bank cannot always interpret the On-Us Field accurately in order to place discrete data elements from
the On-Us Field of the physical document into corresponding discrete fields such as account number, serial
number and transaction codes.
