### ISSUE TITLE
Create example code for X9 files which can be linked to from the README 

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/imagecashletter#39]
**What were you trying to do?**

See code examples for creating X9 files on README.md

**Comment by adamdecaf** [comment]
Is this talking about the following? Could we include the read and write examples without that table? Since there are only two links let's just display them in a paragraph. 

<img width="388" alt="Screen Shot 2019-06-17 at 10 25 51 AM" src="https://user-images.githubusercontent.com/120951/59623950-60a9d280-90ea-11e9-9f88-8235ed0509be.png">
